---
language: java
script: mvn clean verify

before_install:
# os x workaround for JAVA_HOME not set and mvn missing
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
# fixing hostname issue and jdk segfaulting on linux
 - sudo hostname "$(hostname | cut -c1-63)"
 - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts

addons:
  apt:
    packages:
      - libaio1

matrix:
    include:
        - os: linux
          sudo: required
          jdk: openjdk7
        - os: linux
          sudo: required
          jdk: oraclejdk7
        - os: linux
          sudo: required
          jdk: oraclejdk8
        - os: osx
          language: java

notifications:
  email:
    - noamal@gmail.com
    - vilius@wix.com