---
language: java
install: true
script: $TARGET
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libaio1
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

env:
  matrix:
    - TARGET='mvn test'
    - TARGET='mvn install -DskipTests=true'

notifications:
  email:
    - noamal@gmail.com
    - vilius@wix.com
