---
language: java
script: $CMD

env:
  global:
    - CMD='mvn -q -B test -Dtest=TimingOutProcessExecutorTest'
#    - CMD='mvn -q -B verify'

before_install:
# os x - workaround for JAVA_HOME not set and mvn missing
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
# linux - installing libaio1
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install -y libaio1; fi
# to work-around jvm buffer overflow
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo hostname "$(hostname | cut -c1-63)"; fi

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          jdk: openjdk7
#        - os: linux
#          dist: trusty
#          sudo: required
#          jdk: oraclejdk7
#        - os: linux
#          dist: trusty
#          sudo: required
#          jdk: oraclejdk8
#        - os: osx
#          language: java

notifications:
  email:
    - noamal@gmail.com
    - vilius@wix.com